//script to create and populate zipCode_info

use zipCode_info

db.dataZipCode.insertMany([
   { zipCode: "37500026", street: "Rua Santos Pereira", neighborhood: "Centro", city: "Itajubá", state: "MG" }, 
   { zipCode: "37500030", street: "Praça Amélia Braga", neighborhood: "Centro", city: "Itajubá", state: "MG" }, 
   { zipCode: "37500294", street: "Rua José Cândido Pereira dos Santos", neighborhood: "Estiva", city: "Itajubá", state: "MG" }, 
   { zipCode: "37505000", street: "Rua Barão do Rio Branco", neighborhood: "Boa Vista", city: "Itajubá", state: "MG" }, 
   { zipCode: "37505123", street: "", neighborhood: "", city: "", state: "" }, 
   { zipCode: "37505120", street: "", neighborhood: "", city: "", state: "" }, 
   { zipCode: "37505100", street: "", neighborhood: "", city: "", state: "" }, 
   { zipCode: "37505406", street: "Rua Maria de Lourdes Freitas", neighborhood: "Novo Horizonte", city: "Itajubá", state: "MG" }, 
   { zipCode: "37505026", street: "Vila Coronel Carneiro Júnior", neighborhood: "Boa Vista", city: "Itajubá", state: "MG" }, 
   { zipCode: "37500011", street: "Rua Francisco Masseli - de 263/264 a 472/473", neighborhood: "Centro", city: "Itajubá", state: "MG" }, 
   { zipCode: "37500002", street: "Rua Florival Xavier", neighborhood: "Centro", city: "Itajubá", state: "MG" }, 
   { zipCode: "12209003", street: "Rua Capitão Roberto Ferreira Maldos", neighborhood: "Jardim Bela Vista", city: "São José dos Campos", state: "SP" }, 
   { zipCode: "12209590", street: "Rua Alberto Consiglio", neighborhood: "Centro", city: "São José dos Campos", state: "SP" }, 
   { zipCode: "12209675", street: "", neighborhood: "", city: "", state: "" }, 
   { zipCode: "12209670", street: "", neighborhood: "", city: "", state: "" }, 
   { zipCode: "12209600", street: "", neighborhood: "", city: "", state: "" }, 
   { zipCode: "12209000", street: "Avenida Rui Barbosa - até 614/615", neighborhood: "Jardim Bela Vista", city: "São José dos Campos", state: "SP" }, 
   { zipCode: "12210260", street: "Rua Sete de Setembro", neighborhood: "Centro", city: "São José dos Campos", state: "SP" }, 
   { zipCode: "12211190", street: "Travessa Terezinha Savastano", neighborhood: "Vila Alexandrina", city: "São José dos Campos", state: "SP" }, 
   { zipCode: "12211241", street: "Rua Manoel Lemes Palmeira", neighborhood: "Santana", city: "São José dos Campos", state: "SP" }, 
   { zipCode: "12210240", street: "Rua Piracicaba", neighborhood: "Centro", city: "São José dos Campos", state: "SP" }, 
   { zipCode: "60010020", street: "Rua Braga Torres", neighborhood: "Moura Brasil", city: "Fortaleza", state: "CE" }, 
   { zipCode: "60010100", street: "Rua Padre Mororó - até 349/350", neighborhood: "Moura Brasil", city: "Fortaleza", state: "CE" }, 
   { zipCode: "60010610", street: "Rua Dona Leda", neighborhood: "Jacarecanga", city: "Fortaleza", state: "CE" }, 
   { zipCode: "60010000", street: "Avenida Presidente Castelo Branco - até 1999/2000", neighborhood: "Moura Brasil", city: "Fortaleza", state: "CE" }, 
   { zipCode: "60010456", street: "", neighborhood: "", city: "", state: "" }, 
   { zipCode: "60010450", street: "", neighborhood: "", city: "", state: "" }, 
   { zipCode: "60010400", street: "", neighborhood: "", city: "", state: "" }, 
   { zipCode: "60011120", street: "Rua Bela Cruz", neighborhood: "Farias Brito", city: "Fortaleza", state: "CE" }, 
   { zipCode: "60011122", street: "", neighborhood: "", city: "", state: "" }, 
   { zipCode: "60010101", street: "", neighborhood: "", city: "", state: "" }, 
   { zipCode: "23548013", street: "Travessa 1(Cj Tijolinho)", neighborhood: "Sepetiba", city: "Rio de Janeiro", state: "RJ" }, 
   { zipCode: "22793082", street: "Avenida das Américas - de 9303/9304 a 12001/12002", neighborhood: "Barra da Tijuca", city: "Rio de Janeiro", state: "RJ" }, 
   { zipCode: "22793000", street: "Avenida Ayrton Senna - até 659/0660", neighborhood: "Barra da Tijuca", city: "Rio de Janeiro", state: "RJ" }, 
   { zipCode: "22793789", street: "", neighborhood: "", city: "", state: "" }, 
   { zipCode: "22793780", street: "", neighborhood: "", city: "", state: "" }, 
   { zipCode: "22793700", street: "Rua Professor Alfredo Colombo", neighborhood: "Barra da Tijuca", city: "Rio de Janeiro", state: "RJ" }, 
   { zipCode: "20550162", street: "Rua Almirante João Cândido Brasil", neighborhood: "Maracanã", city: "Rio de Janeiro", state: "RJ" }, 
   { zipCode: "22711370", street: "Rua Shalom (Lot Dois Irmãos)", neighborhood: "Curicica", city: "Rio de Janeiro", state: "RJ" }, 
   { zipCode: "22750320", street: "Rua Alcides Lima", neighborhood: "Jacarepaguá", city: "Rio de Janeiro", state: "RJ" }, 
   { zipCode: "22713532", street: "Rua Alcir Ferreira de Matos", neighborhood: "Jacarepaguá", city: "Rio de Janeiro", state: "RJ" }, 
   { zipCode: "66010040", street: "Praça Kennedy", neighborhood: "Campina", city: "Belém", state: "PA" }, 
   { zipCode: "66010130", street: "Travessa Leão XIII", neighborhood: "Campina", city: "Belém", state: "PA" }, 
   { zipCode: "66010000", street: "Avenida Presidente Vargas - até 379/380", neighborhood: "Campina", city: "Belém", state: "PA" }, 
   { zipCode: "66010999", street: "", neighborhood: "", city: "", state: "" }, 
   { zipCode: "66010990", street: "", neighborhood: "", city: "", state: "" }, 
   { zipCode: "66010900", street: "", neighborhood: "", city: "", state: "" }, 
   { zipCode: "66020230", street: "Passagem Dom Pedro", neighborhood: "Cidade Velha", city: "Belém", state: "PA" }, 
   { zipCode: "66023700", street: "Rua Arciprestes Manoel Teodoro - até 543/544", neighborhood: "Batista Campos", city: "Belém", state: "PA" }, 
   { zipCode: "66023709", street: "Rua Veiga Cabral - de 767/768 a 1249/1250", neighborhood: "Campina", city: "Belém", state: "PA" }, 
   { zipCode: "66023680", street: "Vila Abelardo Conduru", neighborhood: "Cidade Velha", city: "Belém", state: "PA" }
])